services:
  backend:
    environment:
      NODE_ENV: development
      APP_ENV: ${APP_ENV:-dev}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    # Expose backend port in dev for debugging
    ports:
      - '4000:4000'
    command: npm run dev
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
      APP_ENV: ${APP_ENV:-dev}
      VITE_HOST: ${VITE_HOST:-0.0.0.0}
      VITE_PORT: ${VITE_PORT:-3000}
      VITE_ALLOWED_HOSTS: ${VITE_ALLOWED_HOSTS:-localhost}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:4000}
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules:
