global:
  resolve_timeout: 5m

route:
  receiver: default
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - severity = "warning"
      receiver: slack
    - matchers:
        - severity = "info"
      receiver: discord

receivers:
  - name: default
    webhook_configs:
      - url: "<FALLBACK_WEBHOOK_URL>"
        send_resolved: true
  - name: slack
    slack_configs:
      - api_url: "<SLACK_WEBHOOK_URL>"
        channel: "#observability"
        send_resolved: true
  - name: discord
    webhook_configs:
      - url: "<DISCORD_WEBHOOK_URL>"
        send_resolved: true
