global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: fastify
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:4000
  - job_name: node_exporter
    static_configs:
      - targets:
          - node-exporter:9100

rule_files:
  - /etc/prometheus/prometheus-alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
