blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/marcantonioschulz/Web-App-Agents-SDK/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/marcantonioschulz/Web-App-Agents-SDK/blob/main/README.md
    about: Read the project documentation
  - name: 🔒 Security Vulnerability
    url: https://github.com/marcantonioschulz/Web-App-Agents-SDK/security/advisories/new
    about: Report a security vulnerability privately
