name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this feature affect?
      options:
        - Backend (Fastify/Node.js)
        - Frontend (React/Vite)
        - Database (PostgreSQL/Prisma)
        - Docker/Deployment
        - CI/CD Pipeline
        - Documentation
        - Multiple components
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the use case.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see... / The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I also thought about... / Currently I work around this by...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - Developers would benefit by...
        - Users would benefit by...
        - The project would benefit by...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could be implemented by:
        1. Adding a new endpoint...
        2. Creating a component...
        3. Modifying the database schema...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Significant improvement
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add mockups, diagrams, or any other context
      placeholder: Screenshots, wireframes, or examples from other projects...

  - type: dropdown
    id: willing-to-implement
    attributes:
      label: Are you willing to implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Maybe with guidance"
        - "No, I need someone else to implement it"
    validations:
      required: false
