name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache root npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-root-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-root-

      - name: Install root dependencies
        run: npm install --prefer-offline

      - name: Run ESLint
        run: npm run lint

  build:
    name: Build (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ matrix.project }}-${{ hashFiles('backend/package.json', 'frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.project }}-
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Cache Prisma Client
        if: matrix.project == 'backend'
        id: cache-prisma
        uses: actions/cache@v4
        with:
          path: backend/node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('backend/prisma/schema.prisma') }}-${{ hashFiles('backend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - name: Generate Prisma Client
        if: matrix.project == 'backend'
        run: npm run prisma:generate

      - name: Build
        run: npm run build --if-present

  test:
    name: Test (${{ matrix.project }})
    runs-on: ubuntu-latest
    environment: TEST_ENV
    needs: [lint, build]
    strategy:
      fail-fast: false
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ matrix.project }}-${{ hashFiles('backend/package.json', 'frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.project }}-
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Restore Prisma Client cache
        if: matrix.project == 'backend'
        uses: actions/cache/restore@v4
        with:
          path: backend/node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('backend/prisma/schema.prisma') }}-${{ hashFiles('backend/package.json') }}

      - name: Generate Prisma Client
        if: matrix.project == 'backend'
        run: npm run prisma:generate

      - name: Run tests
        run: npm test --if-present

  docker:
    name: Build & Push Docker image (${{ matrix.service }})
    runs-on: ubuntu-latest
    environment: TEST_ENV
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_KEY=${{ secrets.API_KEY }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: TEST_ENV
    needs:
      - docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check if deployment is configured
        id: check-deploy
        run: |
          if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy over SSH
        if: steps.check-deploy.outputs.skip == 'false'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            export API_KEY=${{ secrets.API_KEY }}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            cd ${{ secrets.DEPLOY_WORKDIR }}
            docker compose pull
            docker compose up -d --remove-orphans
